//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asmbotGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="asmbotGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IasmbotGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] asmbotGrammarParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] asmbotGrammarParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] asmbotGrammarParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] asmbotGrammarParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.lastLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLastLine([NotNull] asmbotGrammarParser.LastLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.lastLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLastLine([NotNull] asmbotGrammarParser.LastLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.lineContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineContent([NotNull] asmbotGrammarParser.LineContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.lineContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineContent([NotNull] asmbotGrammarParser.LineContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.labelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelDef([NotNull] asmbotGrammarParser.LabelDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.labelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelDef([NotNull] asmbotGrammarParser.LabelDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr([NotNull] asmbotGrammarParser.InstrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr([NotNull] asmbotGrammarParser.InstrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.operandList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperandList([NotNull] asmbotGrammarParser.OperandListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.operandList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperandList([NotNull] asmbotGrammarParser.OperandListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperand([NotNull] asmbotGrammarParser.OperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperand([NotNull] asmbotGrammarParser.OperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.registerOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegisterOperand([NotNull] asmbotGrammarParser.RegisterOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.registerOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegisterOperand([NotNull] asmbotGrammarParser.RegisterOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.memoryOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemoryOperand([NotNull] asmbotGrammarParser.MemoryOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.memoryOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemoryOperand([NotNull] asmbotGrammarParser.MemoryOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.labelOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelOperand([NotNull] asmbotGrammarParser.LabelOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.labelOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelOperand([NotNull] asmbotGrammarParser.LabelOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.immediateOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmediateOperand([NotNull] asmbotGrammarParser.ImmediateOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.immediateOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmediateOperand([NotNull] asmbotGrammarParser.ImmediateOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegister([NotNull] asmbotGrammarParser.RegisterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegister([NotNull] asmbotGrammarParser.RegisterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] asmbotGrammarParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] asmbotGrammarParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmediate([NotNull] asmbotGrammarParser.ImmediateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmediate([NotNull] asmbotGrammarParser.ImmediateContext context);
}
