//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asmbotGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IasmbotGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class asmbotGrammarBaseListener : IasmbotGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] asmbotGrammarParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] asmbotGrammarParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] asmbotGrammarParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] asmbotGrammarParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.lastLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLastLine([NotNull] asmbotGrammarParser.LastLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.lastLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLastLine([NotNull] asmbotGrammarParser.LastLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.lineContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineContent([NotNull] asmbotGrammarParser.LineContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.lineContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineContent([NotNull] asmbotGrammarParser.LineContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.labelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelDef([NotNull] asmbotGrammarParser.LabelDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.labelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelDef([NotNull] asmbotGrammarParser.LabelDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr([NotNull] asmbotGrammarParser.InstrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr([NotNull] asmbotGrammarParser.InstrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.operandList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperandList([NotNull] asmbotGrammarParser.OperandListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.operandList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperandList([NotNull] asmbotGrammarParser.OperandListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] asmbotGrammarParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] asmbotGrammarParser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.registerOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegisterOperand([NotNull] asmbotGrammarParser.RegisterOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.registerOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegisterOperand([NotNull] asmbotGrammarParser.RegisterOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.memoryOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemoryOperand([NotNull] asmbotGrammarParser.MemoryOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.memoryOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemoryOperand([NotNull] asmbotGrammarParser.MemoryOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.labelOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelOperand([NotNull] asmbotGrammarParser.LabelOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.labelOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelOperand([NotNull] asmbotGrammarParser.LabelOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.immediateOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmediateOperand([NotNull] asmbotGrammarParser.ImmediateOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.immediateOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmediateOperand([NotNull] asmbotGrammarParser.ImmediateOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegister([NotNull] asmbotGrammarParser.RegisterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegister([NotNull] asmbotGrammarParser.RegisterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] asmbotGrammarParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] asmbotGrammarParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmbotGrammarParser.immediate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmediate([NotNull] asmbotGrammarParser.ImmediateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmbotGrammarParser.immediate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmediate([NotNull] asmbotGrammarParser.ImmediateContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
